language: php

dist: trusty

php:
  - 7.3

services:
  - docker
jobs:
  include:
    - stage: "Tests"                
      name: "Unit Test PHP"  
      script: 
      - travis_retry composer self-update
      - travis_retry composer install --prefer-source --no-interaction
      - vendor/bin/phpunit

