language: php

dist: trusty

php:
  - 7.3

services:
  - docker

jobs:
  include:
    - stage: "Tests"                
      name: "Unit Test PHP"
      before_script:
        - chmod -R 755 resources/

      script: 
        - travis_retry composer self-update
        - travis_retry composer install --prefer-source --no-interaction
        - docker-compose run cakephp vendor/bin/phpunit
